---
title: "Create occurrence cubes from virtual species"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(gcube)

library(geodata)
library(virtualspecies)

library(sf)
```


```{r}
# Download WorldClim data
worldclim <- worldclim_global(var = "bio", res = 10, path = tempdir())

# Define Western Palearctic extent
wp <- ext(-15, 65, 30, 75)

# Crop to region of interest
worldclim <- crop(worldclim, wp)

# Select specific bioclimatic variables
bio_vars <- c("bio2", "bio5", "bio6", "bio13", "bio14", "bio15")
bio_string <- paste0("bio_", sub("bio", "", bio_vars), collapse = "|")
bio_vars_selected <- names(worldclim)[grepl(bio_string, names(worldclim))]
worldclim <- worldclim[[bio_vars_selected]]

# Step 1: Generate random virtual species
set.seed(123)
random.sp <- generateRandomSp(worldclim)

# Step 2: Distribution bias
case <- limitDistribution(x = random.sp, geographical.limit = "country",
                          area = c("United Kingdom", "Ireland"))

# Step 3: Sample occurrences
sample4 <- sampleOccurrences(case, n = 150)

# Step 4: Convert to sf
st_as_sf(sample4$sample.points, coords = c("x", "y"),
         crs = crs(sample4$original.distribution.raster))
```

